### ISSUE TITLE
Can't Download Custom CSS

### ISSUE THREAD

**Issue by findirfin** [panr/terminal-css#2]
Love the Theme, but when I tries to use the tool at [https://panr.github.io/terminal-css/](https://panr.github.io/terminal-css/) to make a theme, an alert came up that said " Oops, please try again," and in the console there were these errors: 

![image](https://github.com/user-attachments/assets/6207e9eb-b7d9-49bf-bf8a-5f6ddb92547c)

Running on Brave (shields disabled) on Ubuntu

**Comment by panr** [comment]
@findirfin Oops, I'm on it 🏃

**Comment by panr** [comment]
@findirfin Fixed! I messed up with the pathnames for the files... ;-( 

Thanks for letting me know about the issue 🙇
